cmake_minimum_required(VERSION 3.6)

function(GET_COMMON_XSAPI_SOURCE_FILES
         OUT_PUBLIC_SOURCE_FILES
         OUT_PUBLIC_C_SOURCE_FILES
         OUT_COMMON_SOURCE_FILES
         OUT_SYSTEM_SOURCE_FILES
         OUT_LOGGER_SOURCE_FILES
         OUT_SHARED_SOURCE_FILES
         OUT_ACHIEVEMENTS_SOURCE_FILES
         OUT_ACHIEVEMENTS_MANAGER_SOURCE_FILES
         OUT_LEADERBOARD_SOURCE_FILES
         OUT_PRIVACY_SOURCE_FILES
         OUT_PRESENCE_SOURCE_FILES
         OUT_TITLESTORAGE_SOURCE_FILES
         OUT_SOCIAL_SOURCE_FILES
         OUT_SOCIAL_MANAGER_SOURCE_FILES
         OUT_STATS_SOURCE_FILES
         OUT_MATCMAKING_SOURCE_FILES
         OUT_MULTIPLAYER_SOURCE_FILES
         OUT_MULTIPLAYER_MANAGER_SOURCE_FILES
         OUT_STRINGVERIFY_SOURCE_FILES
         OUT_MULTIPLAYERACTIVITY_SOURCE_FILES
         OUT_REALTIMEACTIVITY_MANAGER_SOURCE_FILES
         PATH_TO_ROOT
         )

    set(${OUT_PUBLIC_SOURCE_FILES}
        "${PATH_TO_ROOT}/Include/xsapi-cpp/achievements.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/leaderboard.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/matchmaking.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/multiplayer.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/privacy.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/profile.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/services.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/social.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/system.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/types.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/user_statistics.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/xbox_live_context.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/xbox_service_call_routed_event_args.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/errors.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/http_call.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/http_call_request_message.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/mem.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/social_manager.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/service_call_logging_config.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/multiplayer_manager.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/presence.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/real_time_activity.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/title_storage.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/xbox_live_app_config.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/xbox_live_context_settings.h"
        "${PATH_TO_ROOT}/Include/xsapi-cpp/string_verify.h"
        PARENT_SCOPE
        )

    set(${OUT_PUBLIC_C_SOURCE_FILES}
        "${PATH_TO_ROOT}/Include/xsapi-c/achievements_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/achievements_manager_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/errors_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/presence_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/profile_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/services_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/social_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/social_manager_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/string_verify_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/pal.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/xbox_live_context_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/xbox_live_context_settings_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/xbox_live_global_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/matchmaking_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/multiplayer_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/multiplayer_activity_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/multiplayer_manager_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/notification_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/privacy_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/title_managed_statistics_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/user_statistics_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/leaderboard_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/events_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/real_time_activity_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/types_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/http_call_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/title_storage_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/game_invite_c.h"
        "${PATH_TO_ROOT}/Include/xsapi-c/platform_c.h"
        PARENT_SCOPE
        )
        
    set(${OUT_COMMON_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Common/pch_common.h"
        "${PATH_TO_ROOT}/Source/Services/Common/xbox_live_context.cpp"
        "${PATH_TO_ROOT}/Source/Services/Common/xbox_live_context_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Common/xbox_live_context_settings_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Common/xbox_live_context_settings.cpp"
        "${PATH_TO_ROOT}/Source/Services/Common/xbox_live_context_api.cpp"
        "${PATH_TO_ROOT}/Source/Services/Common/xbox_live_global_api.cpp"
        PARENT_SCOPE
        )
        
    set(${OUT_SYSTEM_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/System/client_operation.h"
        "${PATH_TO_ROOT}/Source/System/local_storage.h"
        "${PATH_TO_ROOT}/Source/System/local_storage.cpp"
        PARENT_SCOPE
        )
        
    set(${OUT_LOGGER_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Shared/Logger/log.cpp"
        "${PATH_TO_ROOT}/Source/Shared/Logger/log.h"
        "${PATH_TO_ROOT}/Source/Shared/Logger/log_entry.cpp"
        "${PATH_TO_ROOT}/Source/Shared/Logger/log_output.cpp"
        "${PATH_TO_ROOT}/Source/Shared/Logger/log_hc_output.cpp"
        "${PATH_TO_ROOT}/Source/Shared/Logger/log_hc_output.h"
        PARENT_SCOPE
        )

    set(${OUT_SHARED_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Shared/xsapi_utils.cpp"
        "${PATH_TO_ROOT}/Source/Shared/xsapi_json_utils.cpp"
        "${PATH_TO_ROOT}/Source/Shared/fault_injection.h"
        "${PATH_TO_ROOT}/Source/Shared/fault_injection.cpp"
        "${PATH_TO_ROOT}/Source/Shared/service_call_routed_handler.h"
        "${PATH_TO_ROOT}/Source/Shared/service_call_routed_handler.cpp"
        "${PATH_TO_ROOT}/Source/Shared/errors_legacy.h"
        "${PATH_TO_ROOT}/Source/Shared/errors.cpp"
        "${PATH_TO_ROOT}/Source/Shared/http_call_request_message.cpp"
        "${PATH_TO_ROOT}/Source/Shared/build_version.h"
        "${PATH_TO_ROOT}/Source/Shared/utils_locales.cpp"
        "${PATH_TO_ROOT}/Source/Shared/web_socket.cpp"
        "${PATH_TO_ROOT}/Source/Shared/xbox_live_app_config_internal.h"
        "${PATH_TO_ROOT}/Source/Shared/xbox_live_app_config.cpp"
        "${PATH_TO_ROOT}/Source/Shared/Shared_macros.h"
        "${PATH_TO_ROOT}/Source/Shared/xsapi_utils.h"
        "${PATH_TO_ROOT}/Source/Shared/xsapi_json_utils.h"
        "${PATH_TO_ROOT}/Source/Shared/perf_tester.h"
        "${PATH_TO_ROOT}/Source/Shared/web_socket.h" 
        "${PATH_TO_ROOT}/Source/Shared/http_headers.h"
        "${PATH_TO_ROOT}/Source/Shared/http_call_request_message_internal.h"
        "${PATH_TO_ROOT}/Source/Shared/internal_mem.h"
        "${PATH_TO_ROOT}/Source/Shared/internal_mem.cpp"
        "${PATH_TO_ROOT}/Source/Shared/async_helpers.h"
        "${PATH_TO_ROOT}/Source/Shared/async_helpers.cpp"
        "${PATH_TO_ROOT}/Source/Shared/internal_errors.h"
        "${PATH_TO_ROOT}/Source/Shared/ref_counter.h"
        "${PATH_TO_ROOT}/Source/Shared/ref_counter.cpp"
        "${PATH_TO_ROOT}/Source/Shared/http_call_api.cpp"
        "${PATH_TO_ROOT}/Source/Shared/http_call_wrapper_internal.h"
        "${PATH_TO_ROOT}/Source/Shared/http_call_wrapper_internal.cpp"
        "${PATH_TO_ROOT}/Source/Shared/global_state.h"
        "${PATH_TO_ROOT}/Source/Shared/global_state.cpp"
        "${PATH_TO_ROOT}/Source/Shared/user.h"
        "${PATH_TO_ROOT}/Source/Shared/string_array.h"
        "${PATH_TO_ROOT}/Source/Shared/user.cpp"
        "${PATH_TO_ROOT}/Source/Shared/enum_traits.h"
        "${PATH_TO_ROOT}/Source/Shared/http_utils.h"
        "${PATH_TO_ROOT}/Source/Shared/http_utils.cpp"
        "${PATH_TO_ROOT}/Source/Shared/internal_types.h"
        "${PATH_TO_ROOT}/Source/Shared/public_utils_legacy.h"
        "${PATH_TO_ROOT}/Source/Shared/public_utils_legacy.cpp"
        PARENT_SCOPE
        )

    set(${OUT_ACHIEVEMENTS_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Achievements/achievement_service_internal.cpp"
        "${PATH_TO_ROOT}/Source/Services/Achievements/achievements_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Achievements/achievements_result.cpp"
        "${PATH_TO_ROOT}/Source/Services/Achievements/achievements_api.cpp"
        "${PATH_TO_ROOT}/Source/Services/Achievements/achievements_subscription.cpp"
        PARENT_SCOPE
        )
        
    set(${OUT_ACHIEVEMENTS_MANAGER_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Achievements/Manager/achievements_manager_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Achievements/Manager/achievements_manager_internal.cpp"
        "${PATH_TO_ROOT}/Source/Services/Achievements/Manager/achievements_manager_api.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_LEADERBOARD_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Leaderboard/Leaderboard_column.cpp"
        "${PATH_TO_ROOT}/Source/Services/Leaderboard/Leaderboard_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Leaderboard/Leaderboard_result.cpp"
        "${PATH_TO_ROOT}/Source/Services/Leaderboard/Leaderboard_row.cpp"
        "${PATH_TO_ROOT}/Source/Services/Leaderboard/Leaderboard_service.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_PRIVACY_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Privacy/privacy_service_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Privacy/Privacy_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Privacy/privacy_api.cpp"
        "${PATH_TO_ROOT}/Source/Services/Privacy/permission_check_result.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_PRESENCE_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Presence/device_presence_change_subscription.cpp"
        "${PATH_TO_ROOT}/Source/Services/Presence/presence_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Presence/presence_device_record.cpp"
        "${PATH_TO_ROOT}/Source/Services/Presence/presence_record.cpp"
        "${PATH_TO_ROOT}/Source/Services/Presence/presence_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Presence/presence_title_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Presence/presence_user_batch_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Presence/title_presence_change_subscription.cpp"
        "${PATH_TO_ROOT}/Source/Services/Presence/presence_api.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_TITLESTORAGE_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/TitleStorage/title_storage_internal.h"
        "${PATH_TO_ROOT}/Source/Services/TitleStorage/title_storage_api.cpp"
        "${PATH_TO_ROOT}/Source/Services/TitleStorage/title_storage_blob_metadata_result.cpp"
        "${PATH_TO_ROOT}/Source/Services/TitleStorage/title_storage_service.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_SOCIAL_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Social/reputation_feedback_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/reputation_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/social_relationship_result.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/social_relationship_change_subscription.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/social_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/social_api.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/social_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Social/profile_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Social/profile_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/profile_api.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_SOCIAL_MANAGER_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/peoplehub_service.h"
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/peoplehub_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/social_graph.h"
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/social_graph.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/social_manager.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/social_manager_api.cpp"
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/social_manager_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/social_manager_user_group.h"
        "${PATH_TO_ROOT}/Source/Services/Social/Manager/social_manager_user_group.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_STATS_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Stats/requested_statistics.cpp"
        "${PATH_TO_ROOT}/Source/Services/Stats/service_configuration_statistic.cpp"
        "${PATH_TO_ROOT}/Source/Services/Stats/statistic.cpp"
        "${PATH_TO_ROOT}/Source/Services/Stats/user_statistics_result.cpp"
        "${PATH_TO_ROOT}/Source/Services/Stats/user_statistics_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Stats/user_statistics_api.cpp"
        "${PATH_TO_ROOT}/Source/Services/Stats/statistic_change_subscription.cpp"
        "${PATH_TO_ROOT}/Source/Services/Stats/user_statistics_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Stats/title_managed_statistics_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Stats/title_managed_statistics_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Stats/title_managed_statistics_api.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_MATCMAKING_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Matchmaking/hopper_statistics_response.cpp"
        "${PATH_TO_ROOT}/Source/Services/Matchmaking/matchmaking_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Matchmaking/match_ticket_details_response.cpp"
        "${PATH_TO_ROOT}/Source/Services/Matchmaking/matchmaking_internal.h"
        PARENT_SCOPE
    )
    
    set(${OUT_MULTIPLAYER_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_activity_handle_post_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_activity_query_post_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_invite_handle_post_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_search_handle_details.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_search_handle_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_query_search_handle_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_session.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_session_member.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_session_reference.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_transfer_handle_post_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_subscription.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_serializers.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/multiplayer_api.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_MULTIPLAYER_MANAGER_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_match_client.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_session_writer.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_client_manager.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_client_pending_reader.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_client_pending_request.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_game_client.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_member.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_game_session.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_lobby_client.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_local_user_manager.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_lobby_session.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_local_user.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_manager.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_manager_utils.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_manager_internal.h"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_event_queue.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_event_args.cpp"
        "${PATH_TO_ROOT}/Source/Services/Multiplayer/Manager/multiplayer_manager_api.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_STRINGVERIFY_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/StringVerify/string_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/StringVerify/string_service_internal.h"
        "${PATH_TO_ROOT}/Source/Services/StringVerify/verify_string_result.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_MULTIPLAYERACTIVITY_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/MultiplayerActivity/multiplayer_activity_api.cpp"
        "${PATH_TO_ROOT}/Source/Services/MultiplayerActivity/multiplayer_activity_internal.h"
        "${PATH_TO_ROOT}/Source/Services/MultiplayerActivity/multiplayer_activity_service.cpp"
        "${PATH_TO_ROOT}/Source/Services/MultiplayerActivity/multiplayer_activity_info.cpp"
        PARENT_SCOPE
    )
    
    set(${OUT_REALTIMEACTIVITY_MANAGER_SOURCE_FILES}
        "${PATH_TO_ROOT}/Source/Services/RealTimeActivityManager/real_time_activity_manager.h"
        "${PATH_TO_ROOT}/Source/Services/RealTimeActivityManager/real_time_activity_manager.cpp"
        "${PATH_TO_ROOT}/Source/Services/RealTimeActivityManager/real_time_activity_connection.h"
        "${PATH_TO_ROOT}/Source/Services/RealTimeActivityManager/real_time_activity_connection.cpp"
        "${PATH_TO_ROOT}/Source/Services/RealTimeActivityManager/real_time_activity_subscription.h"
        "${PATH_TO_ROOT}/Source/Services/RealTimeActivityManager/real_time_activity_api.cpp"
        PARENT_SCOPE
    )
endfunction()