// Copyright (c) Microsoft Corporation
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#pragma once

#include "types_c.h"
#include "xsapi/errors_c.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef enum XSAPI_PRESENCE_DEVICE_TYPE
{
    XSAPI_PRESENCE_DEVICE_TYPE_UNKNOWN,
    XSAPI_PRESENCE_DEVICE_TYPE_WINDOWS_PHONE,
    XSAPI_PRESENCE_DEVICE_TYPE_WINDOWS_PHONE_7,
    XSAPI_PRESENCE_DEVICE_TYPE_WEB,
    XSAPI_PRESENCE_DEVICE_TYPE_XBOX_360,
    XSAPI_PRESENCE_DEVICE_TYPE_PC,
    XSAPI_PRESENCE_DEVICE_TYPE_WINDOWS_8,
    XSAPI_PRESENCE_DEVICE_TYPE_XBOX_ONE,
    XSAPI_PRESENCE_DEVICE_TYPE_WINDOWS_ONE_CORE,
    XSAPI_PRESENCE_DEVICE_TYPE_WINDOWS_ONE_CORE_MOBILE
} XSAPI_PRESENCE_DEVICE_TYPE;

typedef enum XSAPI_USER_PRESENCE_STATE 
{
    XSAPI_USER_PRESENCE_STATE_UNKNOWN,
    XSAPI_USER_PRESENCE_STATE_ONLINE,
    XSAPI_USER_PRESENCE_STATE_AWAY,
    XSAPI_USER_PRESENCE_STATE_OFFLINE
} XSAPI_USER_PRESENCE_STATE;

typedef enum XSAPI_PRESENCE_TITLE_VIEW_STATE 
{
    XSAPI_PRESENCE_TITLE_VIEW_STATE_UNKNOWN,
    XSAPI_PRESENCE_TITLE_VIEW_STATE_FULL_SCREEN,
    XSAPI_PRESENCE_TITLE_VIEW_STATE_FILLED,
    XSAPI_PRESENCE_TITLE_VIEW_STATE_SNAPPED,
    XSAPI_PRESENCE_TITLE_VIEW_STATE_BACKGROUND
} XSAPI_PRESENCE_TITLE_VIEW_STATE;

typedef enum XSAPI_PRESENCE_DETAIL_LEVEL 
{
    XSAPI_PRESENCE_DETAIL_LEVEL_DEFAULT,
    XSAPI_PRESENCE_DETAIL_LEVEL_USER,
    XSAPI_PRESENCE_DETAIL_LEVEL_DEVICE,
    XSAPI_PRESENCE_DETAIL_LEVEL_TITLE,
    XSAPI_PRESENCE_DETAIL_LEVEL_ALL
} XSAPI_PRESENCE_DETAIL_LEVEL;

typedef enum XSAPI_PRESENCE_MEDIA_ID_TYPE 
{
    XSAPI_PRESENCE_MEDIA_ID_TYPE_UNKNOWN,
    XSAPI_PRESENCE_MEDIA_ID_TYPE_BING,
    XSAPI_PRESENCE_MEDIA_ID_TYPE_MEDIA_PROVIDER
} XSAPI_PRESENCE_MEDIA_ID_TYPE;

typedef enum XSAPI_TITLE_PRESENCE_STATE 
{
    XSAPI_TITLE_PRESENCE_STATE_UNKNOWN,
    XSAPI_TITLE_PRESENCE_STATE_STARTED,
    XSAPI_TITLE_PRESENCE_STATE_ENDED
} XSAPI_TITLE_PRESENCE_STATE;

#if defined(__cplusplus)
} // end extern "C"
#endif // defined(__cplusplus)