// 
// GENERATED ON 5/19/2016
// ================================================================
// DO NOT EDIT THIS FILE!
// IF YOU DO NEED TO MAKE CHANGES YOU NEED TO UPDATE
// THE TELEMETRYNAMES.XML FILE FOUND IN THE XboxApp.XbaBond PROJECT
// IN THE /Names FOLDER
// ================================================================
//

#import <Foundation/Foundation.h>

extern NSString* const IDP_PageAction_ChangeRelationship_Action;
extern NSString* const IDP_PageAction_ChangeRelationship_Done;
extern NSString* const IDP_PageView_ChangeRelationship_ChangeRelationshipView;
extern NSString* const IDP_PageAction_DeepLink_SendToStore;
extern NSString* const IDP_PageAction_DeepLink_TitleAchievements;
extern NSString* const IDP_PageAction_DeepLink_TitleHub;
extern NSString* const IDP_PageAction_DeepLink_UserProfile;
extern NSString* const IDP_PageAction_DeepLink_UserSettings;
extern NSString* const IDP_Client_Errors_Failure;
extern NSString* const IDP_Client_Errors_SignedOut;
extern NSString* const IDP_Client_Errors_UINeeded;
extern NSString* const IDP_Client_Errors_UserCancel;
extern NSString* const IDP_PageAction_Errors_Close;
extern NSString* const IDP_PageAction_Errors_GoToBanned;
extern NSString* const IDP_PageAction_Errors_GoToXboxCom;
extern NSString* const IDP_PageAction_Errors_Offline;
extern NSString* const IDP_PageAction_Errors_Retry;
extern NSString* const IDP_PageAction_Errors_RetryAccountCreation;
extern NSString* const IDP_PageAction_Errors_RetrySignIn;
extern NSString* const IDP_PageAction_Errors_RightButton;
extern NSString* const IDP_PageAction_Errors_SignOut;
extern NSString* const IDP_PageView_Errors_Banned;
extern NSString* const IDP_PageView_Errors_Create;
extern NSString* const IDP_PageView_Errors_Generic;
extern NSString* const IDP_PageView_Errors_Offline;
extern NSString* const IDP_Service_Errors_LoadBitmap;
extern NSString* const IDP_Service_Errors_LoadPrivacySettings;
extern NSString* const IDP_Service_Errors_LoadProfile;
extern NSString* const IDP_Service_Errors_LoadSuggestions;
extern NSString* const IDP_Service_Errors_LoadXTOKEN;
extern NSString* const IDP_Service_Errors_ReserveGamerTag;
extern NSString* const IDP_Service_Errors_SetPrivacySettings;
extern NSString* const IDP_PageAction_FriendFinder_Close;
extern NSString* const IDP_PageAction_FriendFinder_ContactsSignUp;
extern NSString* const IDP_PageAction_FriendFinder_ContactsSuggestions;
extern NSString* const IDP_PageAction_FriendFinder_Done;
extern NSString* const IDP_PageAction_FriendFinder_FacebookSignup;
extern NSString* const IDP_PageAction_FriendFinder_FacebookSuggestions;
extern NSString* const IDP_PageAction_FriendFinder_GamertagSearch;
extern NSString* const IDP_PageAction_FriendFinder_GamertagSearchSubmit;
extern NSString* const IDP_PageAction_FriendFinder_GamertagSearchSuccess;
extern NSString* const IDP_PageView_FriendFinder_FriendFinderView;
extern NSString* const IDP_PageAction_FriendFinderContacts_AddFriends;
extern NSString* const IDP_PageAction_FriendFinderContacts_CallMe;
extern NSString* const IDP_PageAction_FriendFinderContacts_ChangeRegion;
extern NSString* const IDP_PageAction_FriendFinderContacts_Close;
extern NSString* const IDP_PageAction_FriendFinderContacts_LinkSuccess;
extern NSString* const IDP_PageAction_FriendFinderContacts_Next;
extern NSString* const IDP_PageAction_FriendFinderContacts_ResendCode;
extern NSString* const IDP_PageAction_FriendFinderContacts_SendInvite;
extern NSString* const IDP_PageAction_FriendFinderContacts_Skip;
extern NSString* const IDP_PageAction_FriendFinderContacts_Unfriend;
extern NSString* const IDP_PageView_FriendFinderContacts_AddPhoneView;
extern NSString* const IDP_PageView_FriendFinderContacts_ChangeRegionView;
extern NSString* const IDP_PageView_FriendFinderContacts_ErrorView;
extern NSString* const IDP_PageView_FriendFinderContacts_FindFriendsView;
extern NSString* const IDP_PageView_FriendFinderContacts_InviteFriendsView;
extern NSString* const IDP_PageView_FriendFinderContacts_OptInView;
extern NSString* const IDP_PageView_FriendFinderContacts_VerifyPhoneView;
extern NSString* const IDP_PageAction_FriendFinderFacebook_AddFacebookFriend;
extern NSString* const IDP_PageAction_FriendFinderFacebook_AddFriendCancel;
extern NSString* const IDP_PageAction_FriendFinderFacebook_FriendFinderBack;
extern NSString* const IDP_PageAction_FriendFinderFacebook_Login;
extern NSString* const IDP_PageAction_FriendFinderFacebook_LoginCancel;
extern NSString* const IDP_PageAction_FriendFinderFacebook_OptInNext;
extern NSString* const IDP_PageAction_FriendFinderFacebook_ShareCancel;
extern NSString* const IDP_PageAction_FriendFinderFacebook_ShareSuccess;
extern NSString* const IDP_PageAction_FriendFinderFacebook_Unfriend;
extern NSString* const IDP_PageView_FriendFinderFacebook_FindFriendsView;
extern NSString* const IDP_PageView_FriendFinderFacebook_LinkAccountView;
extern NSString* const IDP_PageView_FriendFinderFacebook_OptInView;
extern NSString* const IDP_PageView_FriendFinderFacebook_ShareView;
extern NSString* const IDP_PageAction_Introducing_Done;
extern NSString* const IDP_PageView_Introducing_View;
extern NSString* const IDP_PageAction_PeopleHub_Block;
extern NSString* const IDP_PageAction_PeopleHub_BlockOK;
extern NSString* const IDP_PageAction_PeopleHub_Mute;
extern NSString* const IDP_PageAction_PeopleHub_Report;
extern NSString* const IDP_PageAction_PeopleHub_ReportOK;
extern NSString* const IDP_PageAction_PeopleHub_Unblock;
extern NSString* const IDP_PageAction_PeopleHub_ViewXboxApp;
extern NSString* const IDP_PageAction_PeopleHub_ViewXboxAppOK;
extern NSString* const IDP_PageView_PeopleHub_PeopleHubMeView;
extern NSString* const IDP_PageView_PeopleHub_PeopleHubYouView;
extern NSString* const IDP_PageView_PeopleHub_ReportView;
extern NSString* const IDP_PageAction_Signin_AccountSuccess;
extern NSString* const IDP_PageAction_Signin_Signin;
extern NSString* const IDP_PageAction_Signin_TicketSuccess;
extern NSString* const IDP_PageView_Signin_View;
extern NSString* const IDP_PageAction_Signout_Signout;
extern NSString* const IDP_PageAction_Signup_ChangeUser;
extern NSString* const IDP_PageAction_Signup_ClaimGamerTag;
extern NSString* const IDP_PageAction_Signup_ClearGamerTagText;
extern NSString* const IDP_PageAction_Signup_SearchGamertag;
extern NSString* const IDP_PageAction_Signup_SelectSuggestedGamerTag;
extern NSString* const IDP_PageView_Signup_View;
extern NSString* const IDP_PageAction_UserCancel_Cancel;
extern NSString* const IDP_PageAction_Welcome_ChangeUser;
extern NSString* const IDP_PageAction_Welcome_Done;
extern NSString* const IDP_PageView_Welcome_View;
