// 
// GENERATED ON 5/19/2016
// ================================================================
// DO NOT EDIT THIS FILE!
// IF YOU DO NEED TO MAKE CHANGES YOU NEED TO UPDATE
// THE TELEMETRYNAMES.XML FILE FOUND IN THE XboxApp.XbaBond PROJECT
// IN THE /Names FOLDER
// ================================================================
//

#import "UTCIDPNames.h"

NSString* const IDP_PageAction_ChangeRelationship_Action = @"Change Relationship - Action";
NSString* const IDP_PageAction_ChangeRelationship_Done = @"Change Relationship - Done";
NSString* const IDP_PageView_ChangeRelationship_ChangeRelationshipView = @"Change Relationship - Change Relationship View";
NSString* const IDP_PageAction_DeepLink_SendToStore = @"DeepLink - Store Redirect";
NSString* const IDP_PageAction_DeepLink_TitleAchievements = @"DeepLink - GameHub Achievements";
NSString* const IDP_PageAction_DeepLink_TitleHub = @"DeepLink - GameHub";
NSString* const IDP_PageAction_DeepLink_UserProfile = @"DeepLink - User Profile";
NSString* const IDP_PageAction_DeepLink_UserSettings = @"DeepLink - User Settings";
NSString* const IDP_Client_Errors_Failure = @"Client Error Type - Failure";
NSString* const IDP_Client_Errors_SignedOut = @"Client Error Type - Signed out";
NSString* const IDP_Client_Errors_UINeeded = @"Client Error Type - UI Needed";
NSString* const IDP_Client_Errors_UserCancel = @"Client Error Type - User canceled";
NSString* const IDP_PageAction_Errors_Close = @"Errors - Close error screen";
NSString* const IDP_PageAction_Errors_GoToBanned = @"Errors - View enforcement site";
NSString* const IDP_PageAction_Errors_GoToXboxCom = @"Errors - View Xbox.com";
NSString* const IDP_PageAction_Errors_Offline = @"Errors - Offline";
NSString* const IDP_PageAction_Errors_Retry = @"Errors - Try again";
NSString* const IDP_PageAction_Errors_RetryAccountCreation = @"Errors - Retry Account Creation";
NSString* const IDP_PageAction_Errors_RetrySignIn = @"Errors - Retry Signin";
NSString* const IDP_PageAction_Errors_RightButton = @"Errors - Right button";
NSString* const IDP_PageAction_Errors_SignOut = @"Errors - Cancel Signin";
NSString* const IDP_PageView_Errors_Banned = @"Banned error view";
NSString* const IDP_PageView_Errors_Create = @"Create error view";
NSString* const IDP_PageView_Errors_Generic = @"Generic error view";
NSString* const IDP_PageView_Errors_Offline = @"Offline error view";
NSString* const IDP_Service_Errors_LoadBitmap = @"Service Error - Load bitmap";
NSString* const IDP_Service_Errors_LoadPrivacySettings = @"Service Error - Load privacy settings";
NSString* const IDP_Service_Errors_LoadProfile = @"Service Error - Load Profile";
NSString* const IDP_Service_Errors_LoadSuggestions = @"Service Error - Load suggestions";
NSString* const IDP_Service_Errors_LoadXTOKEN = @"Service Error - Load XTOKEN";
NSString* const IDP_Service_Errors_ReserveGamerTag = @"Service Error - Reserve gamertag";
NSString* const IDP_Service_Errors_SetPrivacySettings = @"Service Error - Set privacy settings";
NSString* const IDP_PageAction_FriendFinder_Close = @"Friend Finder - Close";
NSString* const IDP_PageAction_FriendFinder_ContactsSignUp = @"Friend Finder Contacts - Sign Up";
NSString* const IDP_PageAction_FriendFinder_ContactsSuggestions = @"Friend Finder Contacts - Suggestions";
NSString* const IDP_PageAction_FriendFinder_Done = @"Friend Finder - Done";
NSString* const IDP_PageAction_FriendFinder_FacebookSignup = @"Friend Finder - Facebook Signup";
NSString* const IDP_PageAction_FriendFinder_FacebookSuggestions = @"Friend Finder - Facebook Suggestions";
NSString* const IDP_PageAction_FriendFinder_GamertagSearch = @"Friend Finder - Gamertag Search";
NSString* const IDP_PageAction_FriendFinder_GamertagSearchSubmit = @"Friend Finder - Gamertag Search Submit";
NSString* const IDP_PageAction_FriendFinder_GamertagSearchSuccess = @"Friend Finder - Gamertag Search Success";
NSString* const IDP_PageView_FriendFinder_FriendFinderView = @"Friend Finder - View";
NSString* const IDP_PageAction_FriendFinderContacts_AddFriends = @"Friend Finder Contacts - Add Friends";
NSString* const IDP_PageAction_FriendFinderContacts_CallMe = @"Friend Finder Contacts - Call Me";
NSString* const IDP_PageAction_FriendFinderContacts_ChangeRegion = @"Friend Finder Contacts - Change Region";
NSString* const IDP_PageAction_FriendFinderContacts_Close = @"Friend Finder Contacts - Close";
NSString* const IDP_PageAction_FriendFinderContacts_LinkSuccess = @"Friend Finder Contacts - Link Success";
NSString* const IDP_PageAction_FriendFinderContacts_Next = @"Friend Finder Contacts - Next";
NSString* const IDP_PageAction_FriendFinderContacts_ResendCode = @"Friend Finder Contacts - Resend Code";
NSString* const IDP_PageAction_FriendFinderContacts_SendInvite = @"Friend Finder Contacts - Send Invite";
NSString* const IDP_PageAction_FriendFinderContacts_Skip = @"Friend Finder Contacts - Skip";
NSString* const IDP_PageAction_FriendFinderContacts_Unfriend = @"Friend Finder Contacts - Unfriend";
NSString* const IDP_PageView_FriendFinderContacts_AddPhoneView = @"Friend Finder Contacts - Add Phone View";
NSString* const IDP_PageView_FriendFinderContacts_ChangeRegionView = @"Friend Finder Contacts - Change Region View";
NSString* const IDP_PageView_FriendFinderContacts_ErrorView = @"Friend Finder Contacts - Error View";
NSString* const IDP_PageView_FriendFinderContacts_FindFriendsView = @"Friend Finder Contacts - Find Friends View";
NSString* const IDP_PageView_FriendFinderContacts_InviteFriendsView = @"Friend Finder Contacts - Invite Friends View";
NSString* const IDP_PageView_FriendFinderContacts_OptInView = @"Friend Finder Contacts - Opt In View";
NSString* const IDP_PageView_FriendFinderContacts_VerifyPhoneView = @"Friend Finder Contacts - Verify Phone View";
NSString* const IDP_PageAction_FriendFinderFacebook_AddFacebookFriend = @"Friend Finder Facebook - Add Facebook Friend";
NSString* const IDP_PageAction_FriendFinderFacebook_AddFriendCancel = @"Friend Finder Facebook - Add Facebook Friend Cancel";
NSString* const IDP_PageAction_FriendFinderFacebook_FriendFinderBack = @"Friend Finder Facebook - Friend Finder Back";
NSString* const IDP_PageAction_FriendFinderFacebook_Login = @"Friend Finder Facebook - Login";
NSString* const IDP_PageAction_FriendFinderFacebook_LoginCancel = @"Friend Finder Facebook - Login Cancel";
NSString* const IDP_PageAction_FriendFinderFacebook_OptInNext = @"Friend Finder Facebook - Opt In Next";
NSString* const IDP_PageAction_FriendFinderFacebook_ShareCancel = @"Friend Finder Facebook - Upsell Cancel";
NSString* const IDP_PageAction_FriendFinderFacebook_ShareSuccess = @"Friend Finder Facebook - Upsell Success";
NSString* const IDP_PageAction_FriendFinderFacebook_Unfriend = @"Friend Finder Facebook - Unfriend";
NSString* const IDP_PageView_FriendFinderFacebook_FindFriendsView = @"Friend Finder Facebook - Find Friends View";
NSString* const IDP_PageView_FriendFinderFacebook_LinkAccountView = @"Friend Finder Facebook -  Link View";
NSString* const IDP_PageView_FriendFinderFacebook_OptInView = @"Friend Finder Facebook -  Opt In View";
NSString* const IDP_PageView_FriendFinderFacebook_ShareView = @"Friend Finder Facebook - Share View";
NSString* const IDP_PageAction_Introducing_Done = @"Introducing - Done";
NSString* const IDP_PageView_Introducing_View = @"Introducing view";
NSString* const IDP_PageAction_PeopleHub_Block = @"People Hub - Block";
NSString* const IDP_PageAction_PeopleHub_BlockOK = @"People Hub - Block OK";
NSString* const IDP_PageAction_PeopleHub_Mute = @"People Hub - Mute";
NSString* const IDP_PageAction_PeopleHub_Report = @"People Hub - Report";
NSString* const IDP_PageAction_PeopleHub_ReportOK = @"People Hub - Report OK";
NSString* const IDP_PageAction_PeopleHub_Unblock = @"People Hub - Unblock";
NSString* const IDP_PageAction_PeopleHub_ViewXboxApp = @"People Hub - View in Xbox App";
NSString* const IDP_PageAction_PeopleHub_ViewXboxAppOK = @"People Hub - View in Xbox App OK";
NSString* const IDP_PageView_PeopleHub_PeopleHubMeView = @"People Hub - ME View";
NSString* const IDP_PageView_PeopleHub_PeopleHubYouView = @"People Hub - You View";
NSString* const IDP_PageView_PeopleHub_ReportView = @"People Hub Report view";
NSString* const IDP_PageAction_Signin_AccountSuccess = @"Signin - Account acquired";
NSString* const IDP_PageAction_Signin_Signin = @"Signin - Sign in";
NSString* const IDP_PageAction_Signin_TicketSuccess = @"Signin - Ticket acquired";
NSString* const IDP_PageView_Signin_View = @"Sign in view";
NSString* const IDP_PageAction_Signout_Signout = @"Signout - User signed out";
NSString* const IDP_PageAction_Signup_ChangeUser = @"Signup - Signin with different user";
NSString* const IDP_PageAction_Signup_ClaimGamerTag = @"Signup - Claim gamertag";
NSString* const IDP_PageAction_Signup_ClearGamerTagText = @"Signup - Clear gamertag text";
NSString* const IDP_PageAction_Signup_SearchGamertag = @"Signup - Search for gamertag";
NSString* const IDP_PageAction_Signup_SelectSuggestedGamerTag = @"Signup - Select suggested gamertag";
NSString* const IDP_PageView_Signup_View = @"Sign up view";
NSString* const IDP_PageAction_UserCancel_Cancel = @"UserCancel - User canceled";
NSString* const IDP_PageAction_Welcome_ChangeUser = @"Welcome - Change user";
NSString* const IDP_PageAction_Welcome_Done = @"Welcome - Done";
NSString* const IDP_PageView_Welcome_View = @"Welcome view";
