/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_xbox_idp_util_HttpCall */

#ifndef _Included_com_microsoft_xbox_idp_util_HttpCall
#define _Included_com_microsoft_xbox_idp_util_HttpCall
#ifdef __cplusplus
extern "C" {
#endif
    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    setRequestBody
    * Signature: (Ljava/lang/String;)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_setRequestBody__Ljava_lang_String_2
    (JNIEnv *, jobject, jstring);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    setRequestBody
    * Signature: ([B)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_setRequestBody___3B
    (JNIEnv *, jobject, jbyteArray);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    setCustomHeader
    * Signature: (Ljava/lang/String;Ljava/lang/String;)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_setCustomHeader
    (JNIEnv *, jobject, jstring, jstring);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    setRetryAllowed
    * Signature: (Z)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_setRetryAllowed
    (JNIEnv *, jobject, jboolean);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    setLongHttpCall
    * Signature: (Z)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_setLongHttpCall
    (JNIEnv *, jobject, jboolean);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    setContentTypeHeaderValue
    * Signature: (Ljava/lang/String;)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_setContentTypeHeaderValue
    (JNIEnv *, jobject, jstring);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    setXboxContractVersionHeaderValue
    * Signature: (Ljava/lang/String;)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_setXboxContractVersionHeaderValue
    (JNIEnv *, jobject, jstring);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    getResponseAsync
    * Signature: (Lcom/microsoft/xbox/idp/util/HttpCall/Callback;)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_getResponseAsync__Lcom_microsoft_xbox_idp_util_HttpCall_Callback_2
    (JNIEnv *, jobject, jobject);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    create
    * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)J
    */
    JNIEXPORT jlong JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_create
    (JNIEnv *, jclass, jstring, jstring, jstring, jboolean);

    /*
    * Class:     com_microsoft_xbox_idp_util_HttpCall
    * Method:    delete
    * Signature: (J)V
    */
    JNIEXPORT void JNICALL Java_com_microsoft_xbox_idp_util_HttpCall_delete
    (JNIEnv *, jclass, jlong);


#ifdef __cplusplus
}
#endif
#endif

